# This is terrafrom validate workflow for checking terraform syntax
name: terraform-validate
on: 
  pull_request:
    branches: [master]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 0.14.4
      - name: Validate Terraform code
        id: validate
        run: terraform validate -no-color
        working-directory: ./AWS 
       
        
      
        
        
      
        
      
        
  
 
   

    
     
    
