# This is terrafrom validate workflow for checking terraform syntax
name: terraform-validate
on:
  pull_request:
    branches: [master]
jobs:
  plan:
    runs-on: ubuntu-latest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1
      name: Create terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.TERRAFORM }}            
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
        working-directory: ./AWS

        
      
        
        
      
        
      
        
  
 
   

    
     
    
