# This is terrafrom validate workflow for checking terraform syntax
name: terraform-plan
on:
  pull_request:
    branches: [master]
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1

      - name: Terraform init
        id: init
        run: terraform init
        working-directory: AWS

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
        working-directory: AWS
